# Generated by Django 2.2.3 on 2019-07-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_answer_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='question',
            name='liked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
