# Generated by Django 2.2.3 on 2019-07-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190723_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='liked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
